import type { CoverageManifest } from '@paybox/shared';

/**
 * What the Stripe adapter actually serves (spec §31).
 *
 * Generated from the routes the plugin registers and kept in step by
 * `tests/coverage-drift.test.ts`, which fails if this list and the router
 * disagree in either direction. That is what makes the coverage table in
 * `docs/stripe.md` a contract rather than a promise: a route added without an entry
 * here, or an entry left behind after a route is removed, breaks the build.
 *
 * The *prose* in that file -- why something is partial, what differs from the
 * real provider -- stays in Markdown, where it belongs.
 */
export const STRIPE_COVERAGE: CoverageManifest = {
  id: 'stripe',
  label: 'Stripe',
  basePath: '/stripe',
  docs: 'docs/stripe.md',
  entries: [
    { method: 'GET', path: '/checkout/:session', status: 'emulator-only' },
    { method: 'POST', path: '/checkout/:session/pay', status: 'emulator-only', note: 'The hosted page’s own form. Not provider surface.' },
    { method: 'GET', path: '/connect/onboard/:account', status: 'emulator-only' },
    { method: 'POST', path: '/connect/onboard/:account/complete', status: 'emulator-only', note: 'The onboarding page’s form.' },
    { method: 'GET', path: '/setup/:setup', status: 'emulator-only' },
    { method: 'POST', path: '/setup/:setup/complete', status: 'emulator-only', note: 'The setup step-up page’s form.' },
    { method: 'POST', path: '/v1/account_links', status: 'compatible' },
    { method: 'GET', path: '/v1/accounts', status: 'partial' },
    { method: 'POST', path: '/v1/accounts', status: 'partial' },
    { method: 'DELETE', path: '/v1/accounts/:account', status: 'partial' },
    { method: 'GET', path: '/v1/accounts/:account', status: 'partial' },
    { method: 'POST', path: '/v1/accounts/:account', status: 'partial' },
    { method: 'POST', path: '/v1/accounts/:account/reject', status: 'compatible' },
    { method: 'GET', path: '/v1/application_fees', status: 'compatible' },
    { method: 'GET', path: '/v1/application_fees/:fee', status: 'compatible' },
    { method: 'GET', path: '/v1/application_fees/:fee/refunds', status: 'partial' },
    { method: 'POST', path: '/v1/application_fees/:fee/refunds', status: 'partial' },
    { method: 'GET', path: '/v1/balance', status: 'partial' },
    { method: 'GET', path: '/v1/charges', status: 'compatible' },
    { method: 'POST', path: '/v1/charges', status: 'partial' },
    { method: 'GET', path: '/v1/charges/:charge', status: 'compatible' },
    { method: 'POST', path: '/v1/charges/:charge', status: 'compatible' },
    { method: 'POST', path: '/v1/charges/:charge/capture', status: 'partial' },
    { method: 'GET', path: '/v1/checkout/sessions', status: 'compatible' },
    { method: 'POST', path: '/v1/checkout/sessions', status: 'partial' },
    { method: 'GET', path: '/v1/checkout/sessions/:session', status: 'compatible' },
    { method: 'POST', path: '/v1/checkout/sessions/:session/expire', status: 'compatible' },
    { method: 'GET', path: '/v1/checkout/sessions/:session/line_items', status: 'compatible' },
    { method: 'GET', path: '/v1/customers', status: 'partial' },
    { method: 'POST', path: '/v1/customers', status: 'partial' },
    { method: 'GET', path: '/v1/customers/:customer', status: 'partial' },
    { method: 'GET', path: '/v1/invoiceitems', status: 'partial' },
    { method: 'POST', path: '/v1/invoiceitems', status: 'partial' },
    { method: 'DELETE', path: '/v1/invoiceitems/:item', status: 'partial' },
    { method: 'GET', path: '/v1/invoiceitems/:item', status: 'partial' },
    { method: 'GET', path: '/v1/invoices', status: 'compatible' },
    { method: 'POST', path: '/v1/invoices', status: 'partial' },
    { method: 'DELETE', path: '/v1/invoices/:invoice', status: 'partial' },
    { method: 'GET', path: '/v1/invoices/:invoice', status: 'compatible' },
    { method: 'POST', path: '/v1/invoices/:invoice', status: 'partial' },
    { method: 'POST', path: '/v1/invoices/:invoice/finalize', status: 'compatible' },
    { method: 'GET', path: '/v1/invoices/:invoice/lines', status: 'compatible' },
    { method: 'POST', path: '/v1/invoices/:invoice/mark_uncollectible', status: 'compatible' },
    { method: 'POST', path: '/v1/invoices/:invoice/pay', status: 'partial' },
    { method: 'POST', path: '/v1/invoices/:invoice/void', status: 'compatible' },
    { method: 'GET', path: '/v1/payment_intents', status: 'partial' },
    { method: 'POST', path: '/v1/payment_intents', status: 'compatible' },
    { method: 'GET', path: '/v1/payment_intents/:intent', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_intents/:intent', status: 'partial' },
    { method: 'POST', path: '/v1/payment_intents/:intent/cancel', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_intents/:intent/capture', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_intents/:intent/confirm', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_methods', status: 'partial' },
    { method: 'GET', path: '/v1/payment_methods/:paymentMethod', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_methods/:paymentMethod/attach', status: 'compatible' },
    { method: 'POST', path: '/v1/payment_methods/:paymentMethod/detach', status: 'compatible' },
    { method: 'GET', path: '/v1/payouts', status: 'partial' },
    { method: 'POST', path: '/v1/payouts', status: 'partial' },
    { method: 'GET', path: '/v1/payouts/:payout', status: 'partial' },
    { method: 'POST', path: '/v1/payouts/:payout', status: 'partial' },
    { method: 'POST', path: '/v1/payouts/:payout/cancel', status: 'compatible' },
    { method: 'GET', path: '/v1/prices', status: 'partial' },
    { method: 'POST', path: '/v1/prices', status: 'partial' },
    { method: 'GET', path: '/v1/prices/:price', status: 'partial' },
    { method: 'GET', path: '/v1/products', status: 'partial' },
    { method: 'POST', path: '/v1/products', status: 'partial' },
    { method: 'GET', path: '/v1/products/:id', status: 'partial' },
    { method: 'GET', path: '/v1/refunds', status: 'compatible' },
    { method: 'POST', path: '/v1/refunds', status: 'compatible' },
    { method: 'GET', path: '/v1/refunds/:refund', status: 'compatible' },
    { method: 'GET', path: '/v1/setup_intents', status: 'compatible' },
    { method: 'POST', path: '/v1/setup_intents', status: 'compatible' },
    { method: 'GET', path: '/v1/setup_intents/:intent', status: 'compatible' },
    { method: 'POST', path: '/v1/setup_intents/:intent', status: 'partial' },
    { method: 'POST', path: '/v1/setup_intents/:intent/cancel', status: 'compatible' },
    { method: 'POST', path: '/v1/setup_intents/:intent/confirm', status: 'compatible' },
    { method: 'GET', path: '/v1/subscription_items', status: 'partial' },
    { method: 'POST', path: '/v1/subscription_items', status: 'compatible' },
    { method: 'DELETE', path: '/v1/subscription_items/:item', status: 'compatible' },
    { method: 'GET', path: '/v1/subscription_items/:item', status: 'compatible' },
    { method: 'POST', path: '/v1/subscription_items/:item', status: 'compatible' },
    { method: 'GET', path: '/v1/subscriptions', status: 'partial' },
    { method: 'POST', path: '/v1/subscriptions', status: 'partial' },
    { method: 'DELETE', path: '/v1/subscriptions/:id', status: 'compatible' },
    { method: 'GET', path: '/v1/subscriptions/:id', status: 'partial' },
    { method: 'POST', path: '/v1/subscriptions/:id', status: 'partial' },
    { method: 'GET', path: '/v1/transfers', status: 'compatible' },
    { method: 'POST', path: '/v1/transfers', status: 'compatible' },
    { method: 'GET', path: '/v1/transfers/:transfer', status: 'compatible' },
    { method: 'POST', path: '/v1/transfers/:transfer', status: 'compatible' },
    { method: 'GET', path: '/v1/transfers/:transfer/reversals', status: 'partial' },
    { method: 'POST', path: '/v1/transfers/:transfer/reversals', status: 'partial' },
  ],
};
